name: Build Client (Win32)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - run: git clone https://github.com/sampdevelopment/sdk.git sdk

    - run: choco install directx-sdk -y

    - uses: microsoft/setup-msbuild@v1.1

    - shell: cmd
      run: |
        set "DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)"
        msbuild "client.sln" /p:Configuration=Release /p:Platform=x86
