name: Build Client (Win32)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout client
      uses: actions/checkout@v4

    - name: Clone SDK next to client
      run: |
        cd ..
        git clone https://github.com/sampdevelopment/sdk.git sdk
        
    - name: Check directories
      run: |
        cd ..
        dir
        dir sdk
        dir client

    - name: Build Client (Win32)
      run: |
        msbuild client.sln /p:Configuration=Release /p:Platform=Win32
