name: Build Client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout repo + SDK
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    # ================= WINDOWS =================
    - name: Setup MSVC
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build SDK (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd SDK
        msbuild sdk.sln /p:Configuration=Release /p:Platform=Win32

    - name: Build Client (Win32)
      if: matrix.os == 'windows-latest'
      run: |
        msbuild samp-client.sln /p:Configuration=Release /p:Platform=Win32

    # ================= LINUX =================
    - name: Install Linux deps
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y build-essential g++ make

    - name: Build SDK (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd SDK
        make

    - name: Build Client Core (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        make linux
