name: Build Client (Win32)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - run: choco install directx-sdk -y

    - name: Set DXSDK_DIR
      run: |
        echo "DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)" >> $env:GITHUB_ENV
      shell: pwsh

    - uses: microsoft/setup-msbuild@v1.1

    - name: Build Client
      run: msbuild client.sln /p:Configuration=Release /p:Platform=Win32
      shell: cmd
